# Generated by Django 4.2.30 on 2026-05-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Export'), ('UTILITY', 'Utility Portal Export'), ('TRAVEL', 'Travel Platform Export')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('raw_content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NORMALIZED', 'Normalized'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.ingestionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('source_unit', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('NORMALIZED', 'Normalized'), ('FLAGGED', 'Flagged with Issues'), ('APPROVED', 'Approved & Locked')], default='PENDING', max_length=50)),
                ('co2e_emissions', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.ingestionrow')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='api.normalizedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('ADMIN', 'Admin')], default='ANALYST', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_batches', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_values', models.JSONField()),
                ('new_values', models.JSONField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to='api.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.tenant')),
            ],
        ),
    ]
